kind: Namespace
apiVersion: v1
metadata:
  name: kong
  namespace: kong
  labels:
    name: kong
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
        - name: postgres-db
          image: 012765396827.dkr.ecr.us-east-1.amazonaws.com/vishnu-ecr-db:latest
          ports:
            - containerPort: 5432
      imagePullSecrets:
        - name: mykey1
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  labels:
    app: postgres-db
spec:
  ports:
    - port : 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres-db

