apiVersion: v1 
kind: Service 
metadata: 
  name: student-frontend-service
  labels: 
    app: student-frontend
spec: 
  ports: 
    - port : 8000
      protocol: TCP 
      targetPort: 8000
  selector: 
    app: student-frontend